const PUSH_ROUTE = 'PUSH_ROUTE',
      POP_ROUTE = 'POP_ROUTE',
      LOAD_PERSISTED_USER_DATA_REQUEST = 'LOAD_PERSISTED_USER_DATA_REQUEST',
      PERSIST_USER_DATA_SUCCESS = 'PERSIST_USER_DATA_SUCCESS',
      PERSIST_USER_DATA_FAILURE = 'PERSIST_USER_DATA_FAILURE',
      LOAD_USER_DATA_SUCCESS = 'LOAD_USER_DATA_SUCCESS',
      LOAD_USER_DATA_FAILURE = 'LOAD_USER_DATA_FAILURE',
      PERSIST_USER_DATA_REQUEST = 'PERSIST_USER_DATA_REQUEST',
      APPLICATION_IS_BOOTING = 'APPLICATION_IS_BOOTING',
      APPLICATION_FINISHED_BOOTING = 'APPLICATION_FINISHED_BOOTING',
      NAVIGATION_ACTION = 'NAVIGATION_ACTION',
      APPLICATION_ERROR = 'APPLICATION_ERROR';

export {
  PUSH_ROUTE,
  POP_ROUTE,
  LOAD_PERSISTED_USER_DATA_REQUEST,
  PERSIST_USER_DATA_SUCCESS,
  PERSIST_USER_DATA_FAILURE,
  LOAD_USER_DATA_SUCCESS,
  LOAD_USER_DATA_FAILURE,
  PERSIST_USER_DATA_REQUEST,
  APPLICATION_FINISHED_BOOTING,
  APPLICATION_IS_BOOTING,
  NAVIGATION_ACTION,
  APPLICATION_ERROR
};
